### ISSUE TITLE
issue with angular 18

### ISSUE THREAD

**Issue by lepirlouit** [zahmo/ng-formworks#5]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] Bootstrap5FrameworkModule — Bootstrap 5
* [ ] DaisyUIFrameworkModule — DaisyUI
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**
1. with angular 18
2. got error `ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203`

**Expected behavior**
no error is expected

**Screenshots**

**Desktop (please complete the following information):**

n/a

**Log output covering before error and any error statements**

```logs
ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    Angular 3
        RuntimeError
        injectInjectorOnly
        inject2
    MaterialDesignFramework_Factory ng-formworks-material.mjs:3934
    Angular 2
[core.mjs:7192:18](http://localhost:4200/@fs/home/lepirlouit/code/node_modules/@angular/core/fesm2022/core.mjs)
    Angular 32
    RxJS 53
    ZoneAwarePromise Angular
    toPromise RxJS
    loadConfig config.service.ts:12
    appInitializerFn app.module.ts:25
    Angular 26
    <anonyme> main.ts:5
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by zahmo** [comment]
Hi, please update your version of ng-formworks  to version 18, in general ng-formworks versions are compatible with their corresponding angular versions.

**Comment by lepirlouit** [comment]
Thank you for releasing 18.x.x
